export const colors = {
	light: {
		background: "#f8f6f5",
		foreground: "#2D3748",
		card: "#FFFFFF",
		"card-foreground": "#2D3748",
		primary: "#f56e3d",
		"primary-foreground": "#FFFFFF",
		secondary: "#FFD54F",
		"secondary-foreground": "#2D3748",
		muted: "#F1F2F5",
		"muted-foreground": "#96867f",
		accent: "#4DB6AC",
		"accent-foreground": "#FFFFFF",
		destructive: "#F87171",
		"destructive-foreground": "#FFFFFF",
		border: "#E5E7EB",
		input: "#E5E7EB",
		ring: "#f56e3d",
		success: "#22C55E",
		"success-foreground": "#FFFFFF",
		warning: "#EAB308",
		"warning-foreground": "#2D3748",
		info: "#0EA5E9",
		"info-foreground": "#FFFFFF",
		// Attendance
		present: "#DCFCE7",
		"present-text": "#16A34A",
		late: "#FEF3C7",
		"late-text": "#D97706",
		absent: "#FEE2E2",
		"absent-text": "#DC2626",
	},
	dark: {
		background: "#221510",
		foreground: "#E5E7EB",
		card: "#33221b",
		"card-foreground": "#E5E7EB",
		primary: "#f56e3d",
		"primary-foreground": "#FFFFFF",
		secondary: "#FFD54F",
		"secondary-foreground": "#FFFFFF",
		muted: "#33221b",
		"muted-foreground": "#9CA3AF",
		accent: "#4DB6AC",
		"accent-foreground": "#FFFFFF",
		destructive: "#F87171",
		"destructive-foreground": "#E5E7EB",
		border: "#33221b",
		input: "#33221b",
		ring: "#f56e3d",
		success: "#22C55E",
		"success-foreground": "#FFFFFF",
		warning: "#EAB308",
		"warning-foreground": "#FFFFFF",
		info: "#0EA5E9",
		"info-foreground": "#FFFFFF",
		present: "#166534",
		"present-text": "#86EFAC",
		late: "#854D0E",
		"late-text": "#FDE68A",
		absent: "#991B1B",
		"absent-text": "#FCA5A5",
	},
} as const;

export const spacing = {
	xs: 4,
	s: 8,
	m: 16,
	l: 24,
	xl: 32,
} as const;

export const borderRadius = {
	sm: 4,
	md: 8,
	lg: 12,
	xl: 20,
	"2xl": 24,
	"3xl": 32,
	full: 9999,
} as const;

export const fontFamily = {
	sans: ["PlusJakartaSans_400Regular"],
	"sans-medium": ["PlusJakartaSans_500Medium"],
	"sans-semibold": ["PlusJakartaSans_600SemiBold"],
	"sans-bold": ["PlusJakartaSans_700Bold"],
	"sans-extrabold": ["PlusJakartaSans_800ExtraBold"],
	display: ["PlusJakartaSans_700Bold"],
} as const;

export const fontSize = {
	xs: 12,
	sm: 14,
	base: 16,
	lg: 18,
	xl: 20,
	"2xl": 24,
	"3xl": 30,
} as const;
