import type { Prisma } from "@schoolconnect/db";
import { TRPCError } from "@trpc/server";
import PDFDocument from "pdfkit";
import { z } from "zod";
import { assertFeatureEnabled } from "../lib/feature-guards";
import { logger } from "../lib/logger";
import { protectedProcedure, router, schoolFeatureProcedure } from "../trpc";

function generateFormPdf(options: {
	schoolName: string;
	formTitle: string;
	childName: string;
	parentName: string;
	fields: Array<{ id: string; label: string; type: string }>;
	data: Record<string, unknown>;
	signature?: string | null;
	submittedAt: Date;
}): Promise<string> {
	return new Promise((resolve, reject) => {
		const doc = new PDFDocument({ size: "A4", margin: 50 });
		const chunks: Buffer[] = [];

		doc.on("data", (chunk: Buffer) => chunks.push(chunk));
		doc.on("end", () => {
			const pdfBuffer = Buffer.concat(chunks);
			resolve(pdfBuffer.toString("base64"));
		});
		doc.on("error", reject);

		// Header
		doc.fontSize(20).text(options.schoolName, { align: "center" });
		doc.moveDown(0.5);
		doc.fontSize(16).text(options.formTitle, { align: "center" });
		doc.moveDown(1);

		// Meta info
		doc.fontSize(10).fillColor("#666666");
		doc.text(`Child: ${options.childName}`);
		doc.text(`Submitted by: ${options.parentName}`);
		doc.text(`Date: ${options.submittedAt.toLocaleDateString("en-GB")}`);
		doc.moveDown(1);

		// Divider
		doc.moveTo(50, doc.y).lineTo(545, doc.y).stroke("#cccccc");
		doc.moveDown(1);

		// Form responses
		doc.fillColor("#000000");
		for (const field of options.fields) {
			const value = options.data[field.id];
			doc.fontSize(11).font("Helvetica-Bold").text(field.label);
			doc.fontSize(11).font("Helvetica");
			if (field.type === "checkbox") {
				doc.text(value ? "Yes" : "No");
			} else {
				doc.text(String(value ?? "—"));
			}
			doc.moveDown(0.5);
		}

		// Signature
		if (options.signature) {
			doc.moveDown(1);
			doc.fontSize(11).font("Helvetica-Bold").text("Signature:");
			doc.moveDown(0.3);
			try {
				const sigData = options.signature.startsWith("data:")
					? options.signature
					: `data:image/png;base64,${options.signature}`;
				doc.image(sigData, { width: 200, height: 80 });
			} catch {
				doc.fontSize(10).font("Helvetica").text("[Signature on file]");
			}
		}

		// Footer
		doc.moveDown(2);
		doc.fontSize(8).fillColor("#999999").text("Generated by Abridge", { align: "center" });

		doc.end();
	});
}

const fieldSchema = z.object({
	id: z.string().max(100),
	type: z.string().max(50),
	label: z.string().max(200),
	required: z.boolean(),
	options: z.array(z.string().max(200)).optional(),
});

export const formsRouter = router({
	getTemplates: schoolFeatureProcedure.query(async ({ ctx, input }) => {
		assertFeatureEnabled(ctx, "forms");
		return ctx.prisma.formTemplate.findMany({
			where: { schoolId: input.schoolId },
			orderBy: { createdAt: "desc" },
		});
	}),

	createTemplate: schoolFeatureProcedure
		.input(
			z.object({
				title: z.string().min(1).max(200),
				description: z.string().max(2000).optional(),
				fields: z.array(fieldSchema).max(50),
			}),
		)
		.mutation(async ({ ctx, input }) => {
			assertFeatureEnabled(ctx, "forms");
			return ctx.prisma.formTemplate.create({
				data: {
					schoolId: input.schoolId,
					title: input.title,
					description: input.description,
					fields: input.fields as Prisma.InputJsonValue,
				},
			});
		}),

	getTemplate: protectedProcedure
		.input(z.object({ templateId: z.string() }))
		.query(async ({ ctx, input }) => {
			const template = await ctx.prisma.formTemplate.findUnique({
				where: { id: input.templateId },
			});

			if (!template) {
				throw new TRPCError({
					code: "NOT_FOUND",
					message: "Template not found",
				});
			}

			// Verify user has access to this school (as parent or staff)
			const [parentLink, staffLink] = await Promise.all([
				ctx.prisma.parentChild.findFirst({
					where: {
						userId: ctx.user.id,
						child: { schoolId: template.schoolId },
					},
				}),
				ctx.prisma.staffMember.findUnique({
					where: {
						userId_schoolId: {
							userId: ctx.user.id,
							schoolId: template.schoolId,
						},
					},
				}),
			]);

			if (!parentLink && !staffLink) {
				throw new TRPCError({
					code: "FORBIDDEN",
					message: "You do not have access to this template",
				});
			}

			return template;
		}),

	getPendingForms: protectedProcedure
		.input(z.object({ childId: z.string() }))
		.query(async ({ ctx, input }) => {
			const ownership = await ctx.prisma.parentChild.findUnique({
				where: {
					userId_childId: {
						userId: ctx.user.id,
						childId: input.childId,
					},
				},
			});

			if (!ownership) {
				throw new TRPCError({
					code: "FORBIDDEN",
					message: "You are not a parent of this child",
				});
			}

			const child = await ctx.prisma.child.findUnique({
				where: { id: input.childId },
				select: { schoolId: true },
			});

			if (!child) {
				throw new TRPCError({
					code: "NOT_FOUND",
					message: "Child not found",
				});
			}

			return ctx.prisma.formTemplate.findMany({
				where: {
					schoolId: child.schoolId,
					isActive: true,
					responses: {
						none: {
							childId: input.childId,
						},
					},
				},
				orderBy: { createdAt: "desc" },
			});
		}),

	getCompletedForms: protectedProcedure
		.input(z.object({ childId: z.string() }))
		.query(async ({ ctx, input }) => {
			const ownership = await ctx.prisma.parentChild.findUnique({
				where: {
					userId_childId: {
						userId: ctx.user.id,
						childId: input.childId,
					},
				},
			});

			if (!ownership) {
				throw new TRPCError({
					code: "FORBIDDEN",
					message: "You are not a parent of this child",
				});
			}

			return ctx.prisma.formResponse.findMany({
				where: {
					childId: input.childId,
					parentId: ctx.user.id,
				},
				include: {
					template: true,
				},
				orderBy: { submittedAt: "desc" },
			});
		}),

	getFormPdf: protectedProcedure
		.input(z.object({ responseId: z.string() }))
		.query(async ({ ctx, input }) => {
			const response = await ctx.prisma.formResponse.findUnique({
				where: { id: input.responseId },
				select: { pdfData: true, parentId: true },
			});

			if (!response) {
				throw new TRPCError({ code: "NOT_FOUND", message: "Form response not found" });
			}

			if (response.parentId !== ctx.user.id) {
				throw new TRPCError({ code: "FORBIDDEN", message: "You do not have access to this form" });
			}

			if (!response.pdfData) {
				throw new TRPCError({ code: "NOT_FOUND", message: "PDF not available for this form" });
			}

			return { pdfData: response.pdfData };
		}),

	submitForm: protectedProcedure
		.input(
			z.object({
				templateId: z.string(),
				childId: z.string(),
				data: z.record(z.any()),
				signature: z.string().max(500000).optional(),
			}),
		)
		.mutation(async ({ ctx, input }) => {
			const ownership = await ctx.prisma.parentChild.findUnique({
				where: {
					userId_childId: {
						userId: ctx.user.id,
						childId: input.childId,
					},
				},
			});

			if (!ownership) {
				throw new TRPCError({
					code: "FORBIDDEN",
					message: "You are not a parent of this child",
				});
			}

			const [template, child] = await Promise.all([
				ctx.prisma.formTemplate.findUnique({
					where: { id: input.templateId },
					include: { school: { select: { name: true } } },
				}),
				ctx.prisma.child.findUnique({
					where: { id: input.childId },
					select: { firstName: true, lastName: true, schoolId: true },
				}),
			]);

			if (!template) {
				throw new TRPCError({ code: "NOT_FOUND", message: "Template not found" });
			}

			// Verify template belongs to the child's school
			if (child && template.schoolId !== child.schoolId) {
				throw new TRPCError({
					code: "FORBIDDEN",
					message: "This form does not belong to your child's school",
				});
			}

			const form = await ctx.prisma.formResponse.create({
				data: {
					templateId: input.templateId,
					childId: input.childId,
					parentId: ctx.user.id,
					data: input.data,
					signature: input.signature,
				},
			});

			try {
				const fields = template.fields as Array<{ id: string; label: string; type: string }>;
				const pdfBase64 = await generateFormPdf({
					schoolName: template.school.name,
					formTitle: template.title,
					childName: child ? `${child.firstName} ${child.lastName}` : "Unknown",
					parentName: ctx.user.name || ctx.user.email,
					fields,
					data: input.data,
					signature: input.signature,
					submittedAt: form.submittedAt,
				});

				await ctx.prisma.formResponse.update({
					where: { id: form.id },
					data: { pdfData: pdfBase64 },
				});

				logger.info({ formId: form.id }, "PDF generated for form");
			} catch (err) {
				logger.error({ formId: form.id, err }, "Failed to generate PDF");
			}

			return form;
		}),
});
