import {
	Award,
	BadgeCheck,
	BarChart3,
	BookOpen,
	CalendarDays,
	ClipboardCheck,
	Clock,
	CreditCard,
	Database,
	FileText,
	GraduationCap,
	Heart,
	Home,
	Image,
	MessageCircle,
	MessageSquare,
	PenSquare,
	Settings,
	Shield,
	ShieldCheck,
	TrendingUp,
	Trophy,
	Users,
	UtensilsCrossed,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";

export const navIcons: Record<string, LucideIcon> = {
	home: Home,
	chat_bubble: MessageCircle,
	assignment_turned_in: ClipboardCheck,
	payments: CreditCard,
	calendar_month: CalendarDays,
	description: FileText,
	groups: Users,
	favorite: Heart,
	restaurant: UtensilsCrossed,
	sports_soccer: Trophy,
	menu_book: BookOpen,
	auto_stories: BookOpen,
	emoji_events: Award,
	photo_library: Image,
	insights: TrendingUp,
	schedule: Clock,
	chat: MessageSquare,
	settings: Settings,
	edit_square: PenSquare,
	analytics: BarChart3,
	shield: Shield,
	badge: BadgeCheck,
	database: Database,
	shield_person: ShieldCheck,
	school: GraduationCap,
};
